"""Add User model

Revision ID: b2e53e2f75f3
Revises: c91657f285b4
Create Date: 2023-06-04 01:04:18.251143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e53e2f75f3'
down_revision = 'c91657f285b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
